/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'schedule-followup': EventHandler<never, never>
    'followup-notification': EventHandler<never, never>
    'create-application': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'application.created'; data: never }>
    'check-followup': CronHandler<{ topic: 'followup.due'; data: never }>
  }
    
}